name: interactive_predicate_learning

channels:
- anaconda
- nvidia
- pytorch
- conda-forge

dependencies:
  - python=3.9
  - pytorch::pytorch
  - pip
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - conda-forge::pybox2d
  - pip:
    - pygame
    - opencv-python
    - termcolor
    - tabulate
    - hydra-core
    - retry
    - pddlgym
    - astunparse
    - ollama>=0.5.4
