# agent that learn nothing and plan with ground truth pddl
agent: LLMPlanPrecondAgent

defaults:
  - base
  - _self_

# planner to explore in training mode
train_planner: LLMPlanner

# planner in test mode
test_planner: LLMPlanner

# load path
load_path:

# whether use learned predicates & knowledge
use_learned_predicates: True

# whether use few-shot demos
use_few_shot_demos: True

# max number of replan iterations
max_replan_iterations: 3

# whether use both texts and predicates
use_both_text_and_predicates: False