# agent that learn nothing and plan with ground truth pddl
agent: LLMPlanAgent

defaults:
  - base
  - _self_

# planner to explore in training mode
train_planner: LLMPlanner

# planner in test mode
test_planner: LLMPlanner

# load path
load_path: saved_runs/exp_results/CookMeal/train/CookMeal_LearnPDDLAgent_1

# whether use learned predicates & knowledge
use_learned_predicates: True

# whether use few-shot demos
use_few_shot_demos: True

# whether use both texts and predicates
use_both_text_and_predicates: False